<a href="https://colab.research.google.com/github/naresh-marimuthu/Machine-Learning-Projects/blob/main/Similar_Movie_Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import libraries

In [2]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Import Dataset into PD

In [7]:
#Import dataset

movie_dataset = pd.read_csv('/content/movies.csv')

In [8]:
movie_dataset.head()

index  ...           director
0      0  ...      James Cameron
1      1  ...     Gore Verbinski
2      2  ...         Sam Mendes
3      3  ...  Christopher Nolan
4      4  ...     Andrew Stanton

[5 rows x 24 columns]

In [31]:
movie_dataset.shape

(4803, 24)

#Feature extraction

In [10]:
list_of_features = ['genres', 'keywords', 'overview', 'tagline', 'title', 'cast', 'director']

In [16]:
for feature in list_of_features:
  movie_dataset[feature] = movie_dataset[feature].fillna('')

In [17]:
feature_dataset = movie_dataset['genres'] +' '+ movie_dataset['keywords']+' '+ movie_dataset['overview'] +' '+ movie_dataset['tagline']+' '+ movie_dataset['title'] +' '+ movie_dataset['cast'] +' '+ movie_dataset['director']

In [24]:
feature_dataset.head()

0    Action Adventure Fantasy Science Fiction cultu...
1    Adventure Fantasy Action ocean drug abuse exot...
2    Action Adventure Crime spy based on novel secr...
3    Action Crime Drama Thriller dc comics crime fi...
4    Action Adventure Science Fiction based on nove...
dtype: object

In [25]:
feature_dataset.shape

(4803,)

In [27]:
vector = TfidfVectorizer()

In [28]:
feature_vector = vector.fit_transform(feature_dataset)

In [29]:
print(feature_vector)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 313949 stored elements and shape (4803, 31349)>
  Coords	Values
  (0, 575)	0.05874744494063195
  (0, 719)	0.06731130606660389
  (0, 9987)	0.08381139359719003
  (0, 24541)	0.0781825087247856
  (0, 10262)	0.07827254609275694
  (0, 6776)	0.1475450502196134
  (0, 5424)	0.15249563870657573
  (0, 11065)	0.10890934116190694
  (0, 26021)	0.23798089038043096
  (0, 30193)	0.0846146807478439
  (0, 5744)	0.17052678808154256
  (0, 25835)	0.1312041060415005
  (0, 13811)	0.035660637876271516
  (0, 27773)	0.08014292025946683
  (0, 241)	0.19409945746418178
  (0, 4899)	0.1227933750552499
  (0, 20589)	0.1896015461079148
  (0, 17433)	0.14044787266458833
  (0, 14375)	0.040962029716589216
  (0, 8023)	0.17699936996038537
  (0, 28074)	0.030408685842708415
  (0, 18689)	0.14159553128651622
  (0, 20521)	0.36500873710577947
  (0, 20010)	0.04792044316122149
  (0, 29297)	0.15249563870657573
  :	:
  (4802, 21900)	0.08589177004191777
  (4802, 9395)	0.07492

In [30]:
feature_vector.shape

(4803, 31349)

#Generate Cosine Similarity

In [32]:
similarity = cosine_similarity(feature_vector)

In [33]:
print(similarity)

[[1.         0.05399851 0.03084844 ... 0.02434614 0.02809646 0.00665587]
 [0.05399851 1.         0.04098103 ... 0.05353934 0.03667414 0.01552356]
 [0.03084844 0.04098103 1.         ... 0.02269726 0.0425641  0.01228775]
 ...
 [0.02434614 0.05353934 0.02269726 ... 1.         0.02986951 0.03920937]
 [0.02809646 0.03667414 0.0425641  ... 0.02986951 1.         0.02879619]
 [0.00665587 0.01552356 0.01228775 ... 0.03920937 0.02879619 1.        ]]


In [34]:
similarity.shape

(4803, 4803)

#Find Similar Movies

i.Get similar movie

In [45]:
movie_input = input('enter a movie :')

enter a movie :iron man


In [46]:
all_title = movie_dataset['title'].tolist()

In [47]:
print(all_title)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [48]:
close_movies = difflib.get_close_matches(movie_input, all_title)

In [50]:
print(close_movies[0])

Iron Man


In [51]:
close_movie = close_movies[0]

In [59]:
close_movie_index = movie_dataset[movie_dataset.title == close_movie]['index'].values[0]

In [60]:
print(close_movie_index)

68


#Get top movies module

In [71]:
similarity_list = list(enumerate(similarity[close_movie_index]))

In [72]:
print(similarity_list)

[(0, np.float64(0.0485835302550367)), (1, np.float64(0.03440234473398959)), (2, np.float64(0.010301525424956253)), (3, np.float64(0.006223824988768591)), (4, np.float64(0.024872978243300432)), (5, np.float64(0.0259008169757717)), (6, np.float64(0.03206993145086022)), (7, np.float64(0.17626921426749495)), (8, np.float64(0.009146132836817412)), (9, np.float64(0.03410345400610751)), (10, np.float64(0.04042156174481431)), (11, np.float64(0.012769921962739109)), (12, np.float64(0.015787238625059298)), (13, np.float64(0.009948615483041677)), (14, np.float64(0.0713147541656277)), (15, np.float64(0.026307587106320952)), (16, np.float64(0.12800053826988372)), (17, np.float64(0.015569731972069342)), (18, np.float64(0.02088898689243991)), (19, np.float64(0.041104177056169894)), (20, np.float64(0.041642628760046825)), (21, np.float64(0.02715593696595206)), (22, np.float64(0.008760721380106168)), (23, np.float64(0.015824967957481194)), (24, np.float64(0.01691024868011063)), (25, np.float64(0.003304

In [73]:
sorted_similarity_list = sorted(similarity_list, key=lambda x: x[1], reverse=True)

In [74]:
print(sorted_similarity_list)

[(68, np.float64(1.0)), (79, np.float64(0.36788103862186405)), (31, np.float64(0.31501075100469306)), (7, np.float64(0.17626921426749495)), (26, np.float64(0.13439160903673497)), (16, np.float64(0.12800053826988372)), (511, np.float64(0.11415468944095042)), (182, np.float64(0.11049794716683102)), (64, np.float64(0.10488211427755578)), (3623, np.float64(0.10189929703406753)), (94, np.float64(0.09616281195134325)), (4033, np.float64(0.08452663267414778)), (30, np.float64(0.08406768703156887)), (618, np.float64(0.08254620249619271)), (46, np.float64(0.08168728882824966)), (174, np.float64(0.08056589176050645)), (783, np.float64(0.08039355490404285)), (3133, np.float64(0.07693847803449275)), (101, np.float64(0.07693846919217372)), (85, np.float64(0.07666062407625433)), (203, np.float64(0.07513744872750992)), (2875, np.float64(0.07505704712461228)), (198, np.float64(0.07445348298075159)), (3466, np.float64(0.07435760786686184)), (1740, np.float64(0.07431032691583601)), (131, np.float64(0.07

In [75]:
i=0

for movie in sorted_similarity_list:
  movie_index = movie[0]
  if i<20:
    movie_name = movie_dataset[movie_dataset.index==movie_index]['title'].values[0]
    i+=1
    print(movie_name)

Iron Man
Iron Man 2
Iron Man 3
Avengers: Age of Ultron
Captain America: Civil War
The Avengers
X-Men
Ant-Man
X-Men: Apocalypse
Made
Guardians of the Galaxy
Super
Spider-Man 2
Mystery Men
X-Men: Days of Future Past
The Incredible Hulk
Mortdecai
The Devil's Tomb
X-Men: First Class
Captain America: The Winter Soldier


In [78]:
#get close movie based on input:

movie_input = input('enter a movie :')
all_title = movie_dataset['title'].tolist()
close_movies = difflib.get_close_matches(movie_input, all_title)
close_movie = close_movies[0]
print('close movie identified for given input: '+ close_movie)
close_movie_index = movie_dataset[movie_dataset.title == close_movie]['index'].values[0]



#Identity top 30movies for close movie:
similarity_list = list(enumerate(similarity[close_movie_index]))
sorted_similarity_list = sorted(similarity_list, key=lambda x: x[1], reverse=True)


i=0

for movie in sorted_similarity_list:
  movie_index = movie[0]
  if i<20:
    movie_name = movie_dataset[movie_dataset.index==movie_index]['title'].values[0]
    i+=1
    print(movie_name)

enter a movie :lion king
close movie identified for given input: The Lion King
The Lion King
The Addams Family
The Chronicles of Narnia: Prince Caspian
Colombiana
Madagascar
A Man for All Seasons
Darling Lili
Hercules
The Monkey King 2
The Man in the Iron Mask
The King's Speech
The Ghost and the Darkness
House at the End of the Drive
Flipper
Harry Potter and the Philosopher's Stone
Ironclad
The Chronicles of Narnia: The Lion, the Witch and the Wardrobe
DysFunktional Family
Rumble in the Bronx
Nicholas Nickleby
